//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCBDataHarmonizationApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_BankStaff
    {
        public int Id { get; set; }
        public string StaffId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MaritalStatus { get; set; }
        public string Email { get; set; }
        public string Designation { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsProfile { get; set; }
    }
}
