//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCBHarmonization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credential
    {
        public int id { get; set; }
        public string USERNAME { get; set; }
        public string KEY { get; set; }
        public string IV { get; set; }
        public string Date { get; set; }
    }
}
