//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCBHarmonization.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SCBDBEntities : DbContext
    {
        public SCBDBEntities()
            : base("name=SCBDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AccountClass> tbl_AccountClass { get; set; }
        public virtual DbSet<tbl_AccountDesignation> tbl_AccountDesignation { get; set; }
        public virtual DbSet<tbl_AccountType> tbl_AccountType { get; set; }
        public virtual DbSet<tbl_Channel> tbl_Channel { get; set; }
        public virtual DbSet<tbl_Currency> tbl_Currency { get; set; }
        public virtual DbSet<tbl_DestInstType> tbl_DestInstType { get; set; }
        public virtual DbSet<tbl_PaymentTypes> tbl_PaymentTypes { get; set; }
        public virtual DbSet<tbl_SrcInsType> tbl_SrcInsType { get; set; }
        public virtual DbSet<tbl_Status> tbl_Status { get; set; }
        public virtual DbSet<tbl_TransactionCount> tbl_TransactionCount { get; set; }
        public virtual DbSet<TblTransactionType> TblTransactionTypes { get; set; }
        public virtual DbSet<Credential> Credentials { get; set; }
        public virtual DbSet<tbl_Dashboad> tbl_Dashboad { get; set; }
        public virtual DbSet<tbl_GetLoadedData> tbl_GetLoadedData { get; set; }
        public virtual DbSet<tbl_HarmonizationRetrieve> tbl_HarmonizationRetrieve { get; set; }
        public virtual DbSet<tbl_Harmortization> tbl_Harmortization { get; set; }
        public virtual DbSet<TransactionStatus> TransactionStatuses { get; set; }
        public virtual DbSet<StatusesLastFive> StatusesLastFives { get; set; }
        public virtual DbSet<tbl_ResponseSummary> tbl_ResponseSummary { get; set; }
        public virtual DbSet<tbl_TopFive_ResponseSummary> tbl_TopFive_ResponseSummary { get; set; }
        public virtual DbSet<TransactionFailStatu> TransactionFailStatus { get; set; }
        public virtual DbSet<TransactionSuccessStatu> TransactionSuccessStatus { get; set; }
        public virtual DbSet<tbl_Exception> tbl_Exception { get; set; }
        public virtual DbSet<tbl_Exceptionc> tbl_Exceptionc { get; set; }
        public virtual DbSet<tbl_DataRetrieve> tbl_DataRetrieve { get; set; }
        public virtual DbSet<SaveLastLoadedData> SaveLastLoadedDatas { get; set; }
        public virtual DbSet<ExceptionLogger> ExceptionLoggers { get; set; }
        public virtual DbSet<tbl_Exceptionb> tbl_Exceptionb { get; set; }
        public virtual DbSet<tbl_PreHarmonization> tbl_PreHarmonization { get; set; }
        public virtual DbSet<ELMAH_Error> ELMAH_Error { get; set; }
        public virtual DbSet<tbl_SampleData> tbl_SampleData { get; set; }
        public virtual DbSet<LoadingGuidLine> LoadingGuidLines { get; set; }
        public virtual DbSet<Tbl_BankStaff> Tbl_BankStaff { get; set; }
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
        public virtual DbSet<Tbl_CheckExisting> Tbl_CheckExisting { get; set; }
        public virtual DbSet<Tbl_SendData> Tbl_SendData { get; set; }
        public virtual DbSet<Tbl_Credential> Tbl_Credential { get; set; }
        public virtual DbSet<tbl_PreHarmonization_Batch> tbl_PreHarmonization_Batch { get; set; }
        public virtual DbSet<TBL_AUDIT> TBL_AUDIT { get; set; }
        public virtual DbSet<tbl_RawHarmonizationDump> tbl_RawHarmonizationDump { get; set; }
        public virtual DbSet<tbl_RawHarmonizationDumpAlt> tbl_RawHarmonizationDumpAlt { get; set; }
        public virtual DbSet<tbl_PreHarmonization_EbbsChecker> tbl_PreHarmonization_EbbsChecker { get; set; }
        public virtual DbSet<tbl_PreHarmonization_EbbsMaker> tbl_PreHarmonization_EbbsMaker { get; set; }
        public virtual DbSet<tbl_PreHarmonization_ForEbbs> tbl_PreHarmonization_ForEbbs { get; set; }
        public virtual DbSet<tbl_PreHarmonization_ForOpal> tbl_PreHarmonization_ForOpal { get; set; }
        public virtual DbSet<tbl_PreHarmonization_OpalChecker> tbl_PreHarmonization_OpalChecker { get; set; }
        public virtual DbSet<tbl_PreHarmonization_OpalMaker> tbl_PreHarmonization_OpalMaker { get; set; }
    }
}
