//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCBHarmonization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_TransactionCount
    {
        public int Id { get; set; }
        public int SucTransCount { get; set; }
        public int FailTransCount { get; set; }
        public System.DateTime TransDate { get; set; }
    }
}
