//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCBHarmonization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ResponseSummary
    {
        public int Id { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> Successful { get; set; }
        public Nullable<int> Failed { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
    }
}
