//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCBHarmonization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_AUDIT
    {
        public int AUDITID { get; set; }
        public System.DateTime DATETIME { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string DETAIL { get; set; }
        public string IPADDRESS { get; set; }
        public string URL { get; set; }
        public string DEVICENAME { get; set; }
        public string OSNAME { get; set; }
    }
}
