//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCBHarmonization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SendData
    {
        public int Id { get; set; }
        public string Status { get; set; }
        public string Message { get; set; }
        public string Description { get; set; }
        public string Data { get; set; }
        public string SentDate { get; set; }
        public string ReportingDate { get; set; }
    }
}
