//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCBHarmonization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Dashboad
    {
        public int Id { get; set; }
        public Nullable<int> SucTransCount { get; set; }
        public Nullable<int> FailTransCount { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public Nullable<int> SuccessCount { get; set; }
    }
}
