//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SCBHarmonization.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_RawHarmonizationDumpAlt
    {
        public int Id { get; set; }
        public string Amount { get; set; }
        public string Vat { get; set; }
        public string Fee { get; set; }
        public string TransID { get; set; }
        public string SrcAcctNo { get; set; }
        public string SrcInstCode { get; set; }
        public string SrcInstBranchCode { get; set; }
        public string SrcInstType { get; set; }
        public string SrcInstUniqueID { get; set; }
        public string DestAcctNo { get; set; }
        public string DestInstCode { get; set; }
        public string DestInstBranchCode { get; set; }
        public string DestInstType { get; set; }
        public string DestInstUniqueID { get; set; }
        public string PaymentType { get; set; }
        public string BankIncome { get; set; }
        public string TransDate { get; set; }
        public string PsspParty { get; set; }
        public string AccountType { get; set; }
        public string AccountClass { get; set; }
        public string AccountDesignation { get; set; }
        public string Currency { get; set; }
        public string Channels { get; set; }
        public string TransactionTypeCode { get; set; }
        public string PepDesignatedAccount { get; set; }
        public string CypherSecurityLevyExempt { get; set; }
        public string StampDutyExempt { get; set; }
        public string AdditionalField { get; set; }
        public string Inflow { get; set; }
        public string Emtl { get; set; }
        public string ReceiverLocation { get; set; }
        public string FileDepartment { get; set; }
    }
}
